const btn = document.querySelector('.btnmenu')
const sel = document.querySelector('.sel')

btn.addEventListener('click', () => {
    sel.classList.toggle('h300')
    dres_cod.classList.remove('h600')
    reng.classList.remove('h100')
    Leaderinfo.classList.remove('h1000')
    DLeaderinfo.classList.remove('h1000')
    Oldrinfo.classList.remove('h1000')
    Inviter_directorinfo.classList.remove('h1000')
    Inviter_hardinfo.classList.remove('h1000')
    High_compositioninfo.classList.remove('h1000')
    callerinfo.classList.remove('h1000')
    inviteinfo.classList.remove('h1000')
    familyinfo.classList.remove('h1000')
    probationinfo.classList.remove('h1000')
})

const btndres = document.querySelector('.btndres')
const dres_cod = document.querySelector('.dres_cod')

btndres.addEventListener('click', () => {
    dres_cod.classList.toggle('h600')
    sel.classList.remove('h300')
    reng.classList.remove('h100')
    Leaderinfo.classList.remove('h1000')
    DLeaderinfo.classList.remove('h1000')
    Oldrinfo.classList.remove('h1000')
    Inviter_directorinfo.classList.remove('h1000')
    Inviter_hardinfo.classList.remove('h1000')
    High_compositioninfo.classList.remove('h1000')
    callerinfo.classList.remove('h1000')
    inviteinfo.classList.remove('h1000')
    familyinfo.classList.remove('h1000')
    probationinfo.classList.remove('h1000')
})

const ranks = document.querySelector('.ranks')
const reng = document.querySelector('.reng')

ranks.addEventListener('click', () => {
    reng.classList.toggle('h100')
    sel.classList.remove('h300')
    Leaderinfo.classList.remove('h1000')
    DLeaderinfo.classList.remove('h1000')
    Oldrinfo.classList.remove('h1000')
    Inviter_directorinfo.classList.remove('h1000')
    Inviter_hardinfo.classList.remove('h1000')
    High_compositioninfo.classList.remove('h1000')
    callerinfo.classList.remove('h1000')
    inviteinfo.classList.remove('h1000')
    familyinfo.classList.remove('h1000')
    probationinfo.classList.remove('h1000')
    dres_cod.classList.remove('h600')
})






const Leader = document.querySelector('.Leader')
const Leaderinfo = document.querySelector('.Leaderinfo')

Leader.addEventListener('click', () => {
    Leaderinfo.classList.toggle('h1000')
    DLeaderinfo.classList.remove('h1000')
    Oldrinfo.classList.remove('h1000')
    Inviter_directorinfo.classList.remove('h1000')
    Inviter_hardinfo.classList.remove('h1000')
    High_compositioninfo.classList.remove('h1000')
    callerinfo.classList.remove('h1000')
    inviteinfo.classList.remove('h1000')
    familyinfo.classList.remove('h1000')
    probationinfo.classList.remove('h1000')
    sel.classList.remove('h300')
    dres_cod.classList.remove('h600')
})

const DLeader = document.querySelector('.DLeader')
const DLeaderinfo = document.querySelector('.DLeaderinfo')

DLeader.addEventListener('click', () => {
    DLeaderinfo.classList.toggle('h1000')
    Leaderinfo.classList.remove('h1000')
    Oldrinfo.classList.remove('h1000')
    Inviter_directorinfo.classList.remove('h1000')
    Inviter_hardinfo.classList.remove('h1000')
    High_compositioninfo.classList.remove('h1000')
    callerinfo.classList.remove('h1000')
    inviteinfo.classList.remove('h1000')
    familyinfo.classList.remove('h1000')
    probationinfo.classList.remove('h1000')
    sel.classList.remove('h300')
    dres_cod.classList.remove('h600')
})

const Old = document.querySelector('.Old')
const Oldrinfo = document.querySelector('.Oldrinfo')

Old.addEventListener('click', () => {
    Oldrinfo.classList.toggle('h1000')
    DLeaderinfo.classList.remove('h1000')
    Leaderinfo.classList.remove('h1000')
    Inviter_directorinfo.classList.remove('h1000')
    Inviter_hardinfo.classList.remove('h1000')
    High_compositioninfo.classList.remove('h1000')
    callerinfo.classList.remove('h1000')
    inviteinfo.classList.remove('h1000')
    familyinfo.classList.remove('h1000')
    probationinfo.classList.remove('h1000')
    sel.classList.remove('h300')
    dres_cod.classList.remove('h600')
})

const Inviter_director = document.querySelector('.Inviter_director')
const Inviter_directorinfo = document.querySelector('.Inviter_directorinfo')

Inviter_director.addEventListener('click', () => {
    Inviter_directorinfo.classList.toggle('h1000')
    Oldrinfo.classList.remove('h1000')
    DLeaderinfo.classList.remove('h1000')
    Leaderinfo.classList.remove('h1000')
    Inviter_hardinfo.classList.remove('h1000')
    High_compositioninfo.classList.remove('h1000')
    callerinfo.classList.remove('h1000')
    inviteinfo.classList.remove('h1000')
    familyinfo.classList.remove('h1000')
    probationinfo.classList.remove('h1000')
    sel.classList.remove('h300')
    dres_cod.classList.remove('h600')
})

const Inviter_hard = document.querySelector('.Inviter_hard')
const Inviter_hardinfo = document.querySelector('.Inviter_hardinfo')

Inviter_hard.addEventListener('click', () => {
    Inviter_hardinfo.classList.toggle('h1000')
    Inviter_directorinfo.classList.remove('h1000')
    Oldrinfo.classList.remove('h1000')
    DLeaderinfo.classList.remove('h1000')
    Leaderinfo.classList.remove('h1000')
    High_compositioninfo.classList.remove('h1000')
    callerinfo.classList.remove('h1000')
    inviteinfo.classList.remove('h1000')
    familyinfo.classList.remove('h1000')
    probationinfo.classList.remove('h1000')
    sel.classList.remove('h300')
    dres_cod.classList.remove('h600')
})

const High_composition = document.querySelector('.High_composition')
const High_compositioninfo = document.querySelector('.High_compositioninfo')

High_composition.addEventListener('click', () => {
    High_compositioninfo.classList.toggle('h1000')
    Inviter_hardinfo.classList.remove('h1000')
    Inviter_directorinfo.classList.remove('h1000')
    Oldrinfo.classList.remove('h1000')
    DLeaderinfo.classList.remove('h1000')
    Leaderinfo.classList.remove('h1000')
    callerinfo.classList.remove('h1000')
    inviteinfo.classList.remove('h1000')
    familyinfo.classList.remove('h1000')
    probationinfo.classList.remove('h1000')
    sel.classList.remove('h300')
    dres_cod.classList.remove('h600')
})

const caller = document.querySelector('.caller')
const callerinfo = document.querySelector('.callerinfo')

caller.addEventListener('click', () => {
    callerinfo.classList.toggle('h1000')
    High_compositioninfo.classList.remove('h1000')
    Inviter_hardinfo.classList.remove('h1000')
    Inviter_directorinfo.classList.remove('h1000')
    Oldrinfo.classList.remove('h1000')
    DLeaderinfo.classList.remove('h1000')
    Leaderinfo.classList.remove('h1000')
    inviteinfo.classList.remove('h1000')
    familyinfo.classList.remove('h1000')
    probationinfo.classList.remove('h1000')
    sel.classList.remove('h300')
    dres_cod.classList.remove('h600')
})

const invite = document.querySelector('.invite')
const inviteinfo = document.querySelector('.inviteinfo')

invite.addEventListener('click', () => {
    inviteinfo.classList.toggle('h1000')
    callerinfo.classList.remove('h1000')
    High_compositioninfo.classList.remove('h1000')
    Inviter_hardinfo.classList.remove('h1000')
    Inviter_directorinfo.classList.remove('h1000')
    Oldrinfo.classList.remove('h1000')
    DLeaderinfo.classList.remove('h1000')
    Leaderinfo.classList.remove('h1000')
    familyinfo.classList.remove('h1000')
    probationinfo.classList.remove('h1000')
    sel.classList.remove('h300')
    dres_cod.classList.remove('h600')
})

const family = document.querySelector('.family')
const familyinfo = document.querySelector('.familyinfo')

family.addEventListener('click', () => {
    familyinfo.classList.toggle('h1000')
    inviteinfo.classList.remove('h1000')
    callerinfo.classList.remove('h1000')
    High_compositioninfo.classList.remove('h1000')
    Inviter_hardinfo.classList.remove('h1000')
    Inviter_directorinfo.classList.remove('h1000')
    Oldrinfo.classList.remove('h1000')
    DLeaderinfo.classList.remove('h1000')
    Leaderinfo.classList.remove('h1000')
    probationinfo.classList.remove('h1000')
    sel.classList.remove('h300')
    dres_cod.classList.remove('h600')
})

const probation = document.querySelector('.probation')
const probationinfo = document.querySelector('.probationinfo')

probation.addEventListener('click', () => {
    probationinfo.classList.toggle('h1000')
    familyinfo.classList.remove('h1000')
    inviteinfo.classList.remove('h1000')
    callerinfo.classList.remove('h1000')
    High_compositioninfo.classList.remove('h1000')
    Inviter_hardinfo.classList.remove('h1000')
    Inviter_directorinfo.classList.remove('h1000')
    Oldrinfo.classList.remove('h1000')
    DLeaderinfo.classList.remove('h1000')
    Leaderinfo.classList.remove('h1000')
    sel.classList.remove('h300')
    dres_cod.classList.remove('h600')
})